### ISSUE TITLE
Enum 만들어서 CustomException 구현해보기

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#2]
https://github.com/codingspecialist/SpringBoot-CarrotMarket/blob/main/src/main/java/com/example/carrotmarket/enums/ResponseEnum.java

참고

**Comment by JungminK1m** [comment]
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/b28cba9f1abd8d006eae059606cae9471a7b7bf6
기존 JoinCustomException은 삭제하고 Enum 적용해 보았습니다!
