### ISSUE TITLE
관리자 주소 일괄 변경하기

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#3]
앞에 /admin 붙이고 시작하기

**Comment by JungminK1m** [comment]
관리자 관련 컨트롤러 메서드 주소 "/admin"으로 수정했습니다 (｡･∀･)ﾉﾞ 링크 남깁니다
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/2762570a2adb4a9be6f55ecdbc5ad58c509c4583
