### ISSUE TITLE
DB에 조회하지 않고, 해결할 수 있는 부분은 앞에서 처리하자

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#5]
![image](https://user-images.githubusercontent.com/28482278/235098644-9e850e71-4df4-47c2-bfad-0c36b0a4ce03.png)

**Comment by JungminK1m** [comment]
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/a22fbdd4bff02513e2f3e26e688369c9091efce1
수정하였습니다!!
