### ISSUE TITLE
상품 인증 체크

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#6]
![image](https://user-images.githubusercontent.com/28482278/235099222-23c9e363-e8af-4815-959f-3a305cdaacd1.png)

**Comment by JungminK1m** [comment]
관리자가 상품 관리하는 곳들에 전부 인증체크 추가하였습니다😆
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/0ea88a52d1a77cec0d35280ccefa0b67a24e79e5
