### ISSUE TITLE
// 상품 수정     @PostMapping("/product/{productId}/update")     public String update

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#7]

**Comment by codingspecialist** [comment]
- 재고, - 금액 못들어가게 수정하기

**Comment by JungminK1m** [comment]
관리자 상품 등록 시 가격과 금액 0개 이하는 입력 못하도록 자바스크립트와 컨트롤러에서 막았습니다😀
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/ec597ce87022329c353dff414a1d144c7592d4d0
