### ISSUE TITLE
여러번 write한것들은 서비스 사용하기

### ISSUE THREAD

**Issue by codingspecialist** [JungminK1m/Springboot-Product-Study-V5#8]

**Comment by JungminK1m** [comment]
구매자가 상품 구매 또는 취소 시 여러 번 write 하는 부분 서비스 추가하였습니다😄
https://github.com/JungminK1m/Springboot-Product-Study-V5/commit/0ea88a52d1a77cec0d35280ccefa0b67a24e79e5
